# Generated by Django 5.0.1 on 2025-06-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('others', 'Others')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weekday', 'Weekday'), ('punctual', 'Punctual')], max_length=20)),
                ('punctual_day', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('observation', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uses_capacity', models.BooleanField()),
                ('uses_massagist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bath', 'Bath'), ('hosting', 'Hosting'), ('massage', 'Massage'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('massagists_availability', models.IntegerField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_order_id', models.CharField(max_length=255, unique=True)),
                ('book_date', models.DateTimeField()),
                ('hour', models.TimeField()),
                ('people', models.IntegerField()),
                ('comment', models.TextField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_pending', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField()),
                ('checked_in', models.BooleanField()),
                ('checked_out', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('origin', models.CharField(choices=[('web', 'Web'), ('others', 'Others')], max_length=50)),
                ('book_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.admin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
            ],
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('bought_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used', models.BooleanField()),
                ('recipients_email', models.CharField(max_length=255)),
                ('recipients_name', models.CharField(max_length=255)),
                ('recipients_surname', models.CharField(max_length=255)),
                ('gift_name', models.CharField(max_length=255)),
                ('gift_description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('buyer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client')),
            ],
        ),
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_type', models.CharField(choices=[('relax', 'Relax'), ('rock', 'Rock'), ('exfoliation', 'Exfoliation'), ('none', 'None')], max_length=50)),
                ('massage_duration', models.CharField(choices=[('15', '15'), ('30', '30'), ('60', '60')], max_length=50)),
                ('baths_duration', models.TimeField(default='02:00:00')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.availability')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.book')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.giftvoucher')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.producttype'),
        ),
    ]
