# Generated by Django 5.0.1 on 2025-06-17 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_agent_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('massage_type', models.CharField(choices=[('relax', 'Relax'), ('rock', 'Rock'), ('exfoliation', 'Exfoliation'), ('none', 'None')], max_length=50)),
                ('massage_duration', models.CharField(choices=[('15', '15'), ('30', '30'), ('60', '60'), ('0', '0')], max_length=50)),
                ('baths_duration', models.TimeField(default='02:00:00')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='bought_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='gift_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='gift_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses_capacity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses_massagist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsinbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productsingift',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProductBaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bath_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.bathtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baths', to='reservations.product')),
            ],
            options={
                'unique_together': {('product', 'bath_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('hosting_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.hostingtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostings', to='reservations.product')),
            ],
            options={
                'unique_together': {('product', 'hosting_type')},
            },
        ),
        migrations.DeleteModel(
            name='Bath',
        ),
        migrations.DeleteModel(
            name='Hosting',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
