# Generated by Django 5.0.1 on 2025-06-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bathtype_hostingtype_remove_hosting_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbaths',
            options={'verbose_name': 'Product Bath', 'verbose_name_plural': 'Product Baths'},
        ),
        migrations.AlterModelOptions(
            name='producthosting',
            options={'verbose_name': 'Product Hosting', 'verbose_name_plural': 'Product Hostings'},
        ),
    ]
