# Generated by Django 5.0.1 on 2025-06-17 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reservations', '0004_alter_productbaths_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AlterModelOptions(
            name='availabilityrange',
            options={'verbose_name': 'Disponibilidad por rango horario', 'verbose_name_plural': 'Disponibilidades por rango horario'},
        ),
        migrations.AlterModelOptions(
            name='bathtype',
            options={'verbose_name': 'Tipo de Baño', 'verbose_name_plural': 'Tipos de Baños'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='giftvoucher',
            options={'verbose_name': 'Vale Regalo', 'verbose_name_plural': 'Vales Regalo'},
        ),
        migrations.AlterModelOptions(
            name='hostingtype',
            options={'verbose_name': 'Tipo de Alojamiento', 'verbose_name_plural': 'Tipos de Alojamiento'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productbaths',
            options={'verbose_name': 'Baño en Producto', 'verbose_name_plural': 'Baños en Productos'},
        ),
        migrations.AlterModelOptions(
            name='producthosting',
            options={'verbose_name': 'Alojamiento en Producto', 'verbose_name_plural': 'Alojamientos en Productos'},
        ),
        migrations.AlterModelOptions(
            name='productsinbook',
            options={'verbose_name': 'Producto en Reserva', 'verbose_name_plural': 'Productos en Reservas'},
        ),
        migrations.AlterModelOptions(
            name='productsingift',
            options={'verbose_name': 'Producto en Vale Regalo', 'verbose_name_plural': 'Productos en Vales Regalo'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_creator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='origin',
        ),
        migrations.AddField(
            model_name='book',
            name='creator_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del creador'),
        ),
        migrations.AddField(
            model_name='book',
            name='creator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de creador'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.TextField(verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='punctual_day',
            field=models.DateField(blank=True, null=True, verbose_name='Día específico'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='type',
            field=models.CharField(choices=[('weekday', 'Día de la semana'), ('punctual', 'Día específico')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='availabilityrange',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.availability', verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='availabilityrange',
            name='capacity',
            field=models.IntegerField(verbose_name='Aforo'),
        ),
        migrations.AlterField(
            model_name='availabilityrange',
            name='end_time',
            field=models.TimeField(verbose_name='Hora final'),
        ),
        migrations.AlterField(
            model_name='availabilityrange',
            name='initial_time',
            field=models.TimeField(verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='availabilityrange',
            name='massagists_availability',
            field=models.IntegerField(verbose_name='Masajistas disponibles'),
        ),
        migrations.AlterField(
            model_name='bathtype',
            name='baths_duration',
            field=models.TimeField(default='02:00:00', verbose_name='Duración del baño'),
        ),
        migrations.AlterField(
            model_name='bathtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='bathtype',
            name='massage_duration',
            field=models.CharField(choices=[('15', '15 minutos'), ('30', '30 minutos'), ('60', '60 minutos'), ('0', 'Sin masaje')], max_length=50, verbose_name='Duración del masaje'),
        ),
        migrations.AlterField(
            model_name='bathtype',
            name='massage_type',
            field=models.CharField(choices=[('relax', 'Relajante'), ('rock', 'Piedras'), ('exfoliation', 'Exfoliante'), ('none', 'Ninguno')], max_length=50, verbose_name='Tipo de masaje'),
        ),
        migrations.AlterField(
            model_name='bathtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad pagada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount_pending',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad pendiente'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateTimeField(verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='book',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Registrado'),
        ),
        migrations.AlterField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='book',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hour',
            field=models.TimeField(verbose_name='Hora de la reserva'),
        ),
        migrations.AlterField(
            model_name='book',
            name='internal_order_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID de reserva interna'),
        ),
        migrations.AlterField(
            model_name='book',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.IntegerField(default=1, verbose_name='Número de personas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='bought_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='buyer_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.client', verbose_name='Cliente comprador'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='gift_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del regalo'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='gift_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del regalo'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email del destinatario'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del destinatario'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='recipients_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos del destinatario'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='hostingtype',
            name='capacity',
            field=models.IntegerField(verbose_name='Personas'),
        ),
        migrations.AlterField(
            model_name='hostingtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='hostingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses_capacity',
            field=models.BooleanField(default=True, verbose_name='Usa capacidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses_massagist',
            field=models.BooleanField(default=False, verbose_name='Requiere masajista'),
        ),
        migrations.AlterField(
            model_name='productbaths',
            name='bath_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.bathtype', verbose_name='Tipo de baño'),
        ),
        migrations.AlterField(
            model_name='productbaths',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baths', to='reservations.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productbaths',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producthosting',
            name='hosting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.hostingtype', verbose_name='Tipo de alojamiento'),
        ),
        migrations.AlterField(
            model_name='producthosting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostings', to='reservations.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producthosting',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productsinbook',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.availability', verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='productsinbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.book', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='productsinbook',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productsinbook',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productsingift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.giftvoucher', verbose_name='Vale regalo'),
        ),
        migrations.AlterField(
            model_name='productsingift',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productsingift',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='WebBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.book', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva Web',
                'verbose_name_plural': 'Reservas Web',
            },
        ),
    ]
