# Generated by Django 5.0.1 on 2025-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_admin_options_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftvoucher',
            options={'verbose_name': 'Cheque regalo', 'verbose_name_plural': 'Cheques regalo'},
        ),
        migrations.AlterField(
            model_name='book',
            name='hour',
            field=models.TimeField(editable=False, verbose_name='Hora de la reserva'),
        ),
        migrations.AlterField(
            model_name='book',
            name='internal_order_id',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='ID de reserva interna'),
        ),
    ]
