# Generated by Django 5.0.1 on 2025-06-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reservations', '0006_alter_giftvoucher_options_alter_book_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Origen de creación'),
        ),
    ]
