# Generated by Django 5.0.1 on 2025-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_book_creator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cantidad pagada'),
        ),
    ]
