# Generated by Django 5.0.1 on 2025-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_book_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad pagada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='internal_order_id',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='ID de pedido'),
        ),
    ]
