# Generated by Django 5.0.1 on 2025-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_book_amount_paid_alter_book_internal_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.IntegerField(default=1, verbose_name='Nº personas'),
        ),
    ]
