# Generated by Django 5.0.1 on 2025-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_product_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Aforo')),
            ],
            options={
                'verbose_name': 'Aforo',
                'verbose_name_plural': 'Aforos',
            },
        ),
        migrations.RemoveField(
            model_name='availabilityrange',
            name='capacity',
        ),
    ]
