# Generated by Django 5.0.1 on 2025-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_capacity_remove_availabilityrange_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Aforo', 'verbose_name_plural': 'Aforo (único)'},
        ),
        migrations.AlterField(
            model_name='capacity',
            name='value',
            field=models.PositiveIntegerField(default=8, verbose_name='Aforo'),
        ),
    ]
