# Generated by Django 5.0.1 on 2025-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_capacity_options_alter_capacity_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinbook',
            name='availability',
        ),
    ]
