# Generated by Django 5.0.1 on 2025-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_productsinbook_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio'),
        ),
    ]
