# Generated by Django 5.0.1 on 2025-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_bathtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hour',
            field=models.TimeField(verbose_name='Hora de la reserva'),
        ),
    ]
