# Generated by Django 5.0.1 on 2025-06-23 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_book_book_date_alter_book_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsingift',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='productsingift',
            name='product',
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='book',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reservations.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reservations.product', verbose_name='Producto'),
        ),
        migrations.DeleteModel(
            name='ProductsInBook',
        ),
        migrations.DeleteModel(
            name='ProductsInGift',
        ),
    ]
