# Generated by Django 5.0.1 on 2025-06-24 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_remove_productsingift_gift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Día de restricción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Restricción',
                'verbose_name_plural': 'Restricciones',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='BookLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del log')),
                ('comment', models.TextField(verbose_name='Comentario del log')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.book', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Log de Reserva',
                'verbose_name_plural': 'Logs de Reservas',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='ConstraintRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_time', models.TimeField(verbose_name='Hora inicial')),
                ('end_time', models.TimeField(verbose_name='Hora final')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.constraint', verbose_name='Restricción')),
            ],
            options={
                'verbose_name': 'Rango de Restricción',
                'verbose_name_plural': 'Rangos de Restricción',
                'ordering': ['initial_time'],
            },
        ),
    ]
