# Generated by Django 5.0.1 on 2025-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_constraint_booklogs_constraintrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
