# Generated by Django 5.0.1 on 2025-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_book_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftvoucher',
            name='used',
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='people',
            field=models.IntegerField(default=1, verbose_name='Nº personas'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente pago'), ('paid', 'Pagado'), ('used', 'Usado')], default='pending_payment', max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio'),
        ),
    ]
