services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  celery:
    build: ./backend
    command: celery -A myproject worker -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  redis_data: 